export interface IUser {
    id_user?: number,
    email: string,
    pass: string,
    name: string,
    lastname: string,
    maternalsurname: string,
    dob: Date,
    street: string,
    number: string,
    municipality: string,
    city: string,
    state: string,
    phone: string,
    gender: number,
    usertype: string,
    position?: string,
    license?: string,
    image?: string,
    lastpurchase?: Date,
    active: number
}

export interface ICustomer {
    id_user?: number,
    email: string,
    pass?: string,
    confpass?: string,
    name: string,
    lastname: string,
    maternalsurname: string,
    dob: Date,
    street: string,
    number: string,
    municipality: string,
    city: string,
    state: string,
    phone: string,
    gender: number,
    usertype: string,
    image?: string,
    active: number,
    verified: 'VERIFIED' | 'UNVERIFIED' | 'REMOVED'
}